language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci

script:
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
